version: '3'

services:
  # app:
  #   build: .
  #   container_name: api-node
  #   restart: always
  #   depends_on:
  #     - redis
  #   ports:
  #     - "3333:3333"
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules
  #   environment:
  #     - REDIS_HOST=redis
  #     - REDIS_PORT=6379

  redis:
    image: redis:alpine
    container_name: redis-api-node
    restart: always
    ports:
      - "6379:6379"