services:
  app:
    build: .
    container_name: api-node
    restart: always
    depends_on:
      - redis
      - postgres
    ports:
      - "3333:3333"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/mydatabase

  redis:
    image: redis:alpine
    container_name: redis-api-node
    restart: always
    ports:
      - "6379:6379"

  postgres:
    image: postgres:15-alpine
    container_name: postgres-api-node
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydatabase
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
